language: node_js
sudo: false
node_js:
- '12'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
- npm install coveralls
script:
- npm run coverage
after_success:
- npm run coveralls
cache:
  directories:
    - node_modules
